apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-javatest-sqdd
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:1344b160de12a445f7b7f9194a5fda260a95c4de83a19e4be6580e13bc47ebc9
        name: my-java-springboot
        resources: {}
status: {}
