apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-amjp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-amjp
    app.kubernetes.io/part-of: my-app-1
  name: dc-metro-map-amjp
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dc-metro-map-amjp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dc-metro-map-amjp
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:43ba76c325ac1d637489af984e2d5a8d437f543600d3f18a7683ebec02be04f5
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
