apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-vobr
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:ac747e5921fe6a0951bf8477815aeb74ad86862c3d005a78f19993334d166228
        name: my-nodejs
        resources: {}
status: {}
