apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-javatest-sqdd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-javatest-sqdd
    app.kubernetes.io/part-of: my-app-1
  name: devfile-javatest-sqdd
  namespace: karthik-jk-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: devfile-javatest-sqdd
status:
  loadBalancer: {}
