apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-express-hello-x6mz
  namespace: karthik-jk-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:3ac1ef71fcecf105b2d052c1fb14aec93810840f21cf325fd3a30c84f3d7df84
        name: my-nodejs
        resources: {}
status: {}
